# Generated by Django 5.1.7 on 2025-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FloatField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('skills', models.TextField()),
                ('responsibility', models.TextField()),
            ],
        ),
    ]
